version: "3"

services:
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: "${COMPOSE_IMAGE:-local-citus}:latest"
    ports: ["${COORDINATOR_EXTERNAL_PORT:-5432}:5432"]
    labels: ["com.citusdata.role=Master"]
    environment: &AUTH
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGUSER: "${POSTGRES_USER:-postgres}"
      PGPASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
    networks:
      pg_net:
        ipv4_address: 172.16.238.10

  worker:
    image: "${COMPOSE_IMAGE:-local-citus}:latest"
    labels: ["com.citusdata.role=Worker"]
    depends_on: { master: { condition: service_healthy } }
    environment: *AUTH
    shm_size: 1gb
    networks:
      pg_net:

  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: "citusdata/membership-manager:latest"
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    depends_on: { master: { condition: service_healthy } }
    environment: *AUTH
    networks:
      pg_net:

networks:
  pg_net:
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
