version: '2.4'

services:
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: 'local-citus:latest'
    labels: ['com.citusdata.role=Master']
    networks:
      pg_net:
        ipv4_address: 172.16.238.10
    environment:
    - POSTGRES_DB=citus
  
  worker:
    image: 'local-citus:latest'
    labels: ['com.citusdata.role=Worker']
    networks:
      pg_net:
    depends_on: { manager: { condition: service_healthy } }
    environment:
    - POSTGRES_DB=citus
    shm_size: 1gb

  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: 'citusdata/membership-manager:0.2.0'
    networks:
      pg_net:
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    depends_on: { master: { condition: service_healthy } }
    environment:
    - POSTGRES_DB=citus

networks:
  pg_net:
    enable_ipv6: false
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
